version: 1.2
workflows:
    - name: map_pubmed_ids_to_pgs_catalog
      subclass: WDL
      primaryDescriptorPath: /map_pubmed_ids_to_pgs_catalog.wdl
    - name: pgs_variant_overlap
      subclass: WDL
      primaryDescriptorPath: /pgs_variant_overlap.wdl
    - name: filter_pgs_catalog_scores
      subclass: WDL
      primaryDescriptorPath: /filter_pgs_catalog_scores.wdl
      testParameterFile: /filter_pgs_catalog_scores.json
