---
title: "PRIMED Publications in PGS catalog"
format:
  html:
    code-fold: true
params:
    mapping_results_file: NA
---

```{r library}
library(tidyverse)
library(knitr)
```

```{r}
mapping_results = read_tsv(params$mapping_results_file, show_col_types=FALSE)
```

# Number of unique PubmedIDs that have a record in PGS Catalog

## Overall

```{r}
x <- mapping_results %>% select(pm_id) %>% distinct() %>% nrow()
```

`r x` total PRIMED PMIDs.

## Unique PubmedIDs by PGS type

```{r}
mapping_results %>% select(pm_id, pgs_type) %>% distinct() %>% group_by(pgs_type) %>% count() %>% kable()
```


## Number of PGS by PubmedID and type

```{r}
mapping_results %>%
    group_by(pm_id, pgs_type) %>%
    count() %>%
    pivot_wider(names_from="pgs_type", values_from="n", values_fill=list(n=0)) %>%
    kable()
```

## Number of unique PGS by trait
```{r}
mapping_results %>%
    select(pgs_id, trait_reported) %>%
    distinct() %>%
    group_by(trait_reported) %>%
    count() %>%
    kable()
```

## Number of unique pubs by trait

```{r}
mapping_results %>%
    select(pm_id, trait_reported) %>%
    distinct() %>%
    group_by(trait_reported) %>%
    count() %>%
    kable()
```

## PGS info

```{r}
mapping_results %>%
    select(pgs_id, trait_reported, ancestry_broad) %>%
    distinct() %>%
    kable()
```


## Number of unique PGS by ancestry
```{r}
mapping_results %>%
    select(pgs_id, ancestry_broad) %>%
    distinct() %>%
    group_by(ancestry_broad) %>%
    count() %>%
    kable()
```

## Number of unique pubs by ancestry

```{r}
mapping_results %>%
    select(pm_id, ancestry_broad) %>%
    distinct() %>%
    group_by(ancestry_broad) %>%
    count() %>%
    kable()
```

# Full mapping results

```{r}
mapping_results %>% kable()
```
